config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      database: main
      password: LptnxTmNWvWo_pjP7FaH
      port: 3306
      schema: main
      server: localhost
      type: mysql
      username: airbyte
  target: prod
